# -*- coding: utf-8 -*-
"""sufi.p

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d7ZABaEtXUsC5_SRsN8jjGkm_7OdtWXd

##Observations
####This are the some liblaries of python with the help of this liblaries
####which are commonly used for data analysis, numerical computation, and data visualization.
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

"""####Observation
#####This code connects my Google Drive to  Google Colab . It allows you to access files stored in Google Drive
"""

from google.colab import drive
drive.mount('/content/drive')

"""####Observations
#####This line loads the dataset named ecommerce.sales.csv from my Google Drive into a pandas DataFrame called data.
"""

data = pd.read_csv('/content/drive/MyDrive/data/ecommerce.sales.csv')
data

"""####Observations
#####This are the top 20 rows of dataset
"""

data.head(20)

"""####Observations
#####This are the bottom 20 Rows of DataSet

"""

data.tail(20)

"""##2.DATA CLEANING

####Observations
#####This line of code we described the Our DataSet
"""

data.describe()

data.duplicated().sum()

"""####Observations
#####This code i used for removing dyblicates values
"""

data = data.drop_duplicates()

data.duplicated().sum()

"""#####Observations
####This Line of code for Dytypes of our DataSet

"""

data.dtypes

"""#####Observations
####This Line of code for the shape
####IT means that how many columns and rows present in the dataset

"""

data.shape

"""#####Observations
This are the some unique values presentin the dataset
"""

data.nunique()

"""#####Observations
####This line of code How many null values present in the table
"""

data.isnull().sum()

"""#####Observations
####This line of code i written because this code drop a nulll vlues fromm the table
"""

data = data.dropna(subset=['Product_Category'])
data = data.dropna(subset=['Price'])
data = data.dropna(subset=['Payment_Method'])
data = data.dropna(subset=['Country'])

"""#####Observations
####This line of code after droping all the null values
"""

data.isnull().sum()

data.info()

"""#####Observations
####This line of code i written for
####I can convert object into category type so thats why i written this
"""

data['Order_ID'] = data['Order_ID'].astype("category")
data['Customer_ID'] = data['Customer_ID'].astype("category")
data['Product_Category'] = data['Product_Category'].astype("category")
data['Payment_Method'] = data['Payment_Method'].astype("category")
data['Country'] = data['Country'].astype("category")
data['Order_Date'] = data['Order_Date'].astype("category")

"""#####Observations
####After converting object into Category column

"""

data.duplicated().sum()

data.info()

"""####Observations So far
#####We im port sum liblaries of Pythons
#####I Read my csv file my google drive to goole colab
#####after that i taken the top 20 rows of dataset and last 20 rows of data set
#####I taken the information about the dataset
#####i described dataset in the details
#####I drop the some null values rom the table
#####After that i converted object in category type

#Univarient Analysis On Numerical Columns

####Observations
#####This line of code for the all the numerical columns
"""

all_numerical_cols_data = data[['Quantity', 'Price', 'Order_Date']]
all_numerical_cols_data

"""####Observations
#####This line of code for the quantity of the numerical column
"""

data['Quantity'].value_counts()

"""####Observations
#####This line of code for the numerical we devided into Percentage
"""

data['Quantity'].value_counts(normalize=True)*100

"""####Observations
#####This line of code only two columns are there in the numerical columns
"""

numeric_columns  = data.select_dtypes(include=['number'])
numeric_columns

"""####Observation
This code reads the dataset ecommerce.sales.csv and selects only the numerical columns from it. The output displays the names of all numeric columns present in the dataset.

"""

data = pd.read_csv('/content/drive/MyDrive/data/ecommerce.sales.csv')

numerical_data = data.select_dtypes(include=['number'])

print("Numeric columns in the dataset:")
print(numerical_data.columns)

"""####Observation
#####THis line of code for the hisplot
#####It means that the data will in grap type we called it histplot
"""

sns.histplot(data=data, x="Quantity", color='Black', kde=True)
plt.show()

sns.histplot(data=data,x="Quantity",color='Red')
plt.show()

numerical_data['Quantity'].plot.box()

"""####Observations
#####
This code creates a **box plot** for the column Quantity using Seaborn. It visually shows how the Quantity values are spread out, including the **median, quartiles, and any outliers**. The box is colored blue, and the plot helps identify if there are **extreme or unusual values** in the Quantity data.

"""

sns.boxplot(data=data,x="Quantity",color='Blue')
plt.show()

"""####Observation
This code creates a vertical box plot for the Quantity column from the numerical_data dataset. It shows the **distribution, central value median, and presence of outliers for Quantity. The vertical orientation makes it easier to observe how the data values are spread along the Y-axis.

"""

sns.boxplot(data=numerical_data['Quantity'],orient='v')

sns.catplot(data=numerical_data['Quantity'], kind='box')

"""####Observations
Observation
This code generates a Kernel Density Estimate (KDE) plot for the Quantity column. It displays the **probability distribution** of Quantity values as a smooth curve. The shape of the curve helps understand how the data is distributed — whether its  skewed, normal, or has multiple peaks

"""

sns.kdeplot(data=numerical_data['Quantity'])

"""####observations
This plot for the numericsl data type quantity i use in the code histplot
"""

sns.histplot(data=numerical_data['Quantity'] ,kde=True)

"""####Observation
This code creates a histogram for the Price column, shown in yellow. It displays how the Price values are distributed across different ranges. The height of each bar represents how many observations fall within that range, helping identify patterns such

"""

sns.histplot(data=data,x="Price",color='Yellow')
plt.show()

"""####Observation
This code is used to create a box plot for the Price column to show its distribution, median, and outliers

"""

sns.catplot(data=numerical_data['Price'], kind='box')

"""###Common Method for Univariate Analysis - Numerical"""

def univariate_numerical(data):
  fig, axes = plt.subplots(3, 1, figsize=(10, 15))
  sns.histplot(data=data,ax=axes[0])
  sns.boxplot(data=data,orient='h',ax=axes[1])
  sns.kdeplot(data=data,ax=axes[2])

"""####Observations
#####This are the numerical columns
"""

numerical_data.columns

"""####Observation
This code performs univariate analysis on the Quantity column to show its distribution, spread, and outliers

"""

univariate_numerical(data['Quantity'])

"""##UNIVARIATE ANALYSIS - CATEGORICAL COLUMN

####Observations
#####This are the categorical coumns
"""

data.columns

"""####Observation
This code selects all categorical columns data type object from the dataset and prints them, displaying the **text or label-based data such as names,
categories, or IDs.

"""

categorical_data = data.select_dtypes(include=['object'])
print(categorical_data)

categorical_data.columns

"""####Observation
#####for the categorical column for Payment category



"""

data['Product_Category'].value_counts().plot.bar()

"""####Observations
#####This plot for the categorical column for product category
#####This time we use the countplot for the product categories

"""

sns.countplot(data=data, x='Product_Category', color='Green')

"""####Observations
#####this plot also for the categorical column Payment method
#####This time we catplot how many types of paymenst are availabale
"""

sns.catplot(data=data, x='Payment_Method',kind='count',color='Brown')

"""##BIVARIATE ANALYSIS

(only for numerical columns):
"""

numerical_data = data.select_dtypes(include=[np.number])

plt.figure(figsize=(10, 8))
sns.heatmap(numerical_data.corr(), annot=True)
plt.show()

"""####Observations
#####This are the numerical clomns of bivarient Analysis
"""

numerical_data.corr()

"""####Observations
#####Most data points are scattered without a clear pattern, indicating no strong relationship between Quantity and Price.


"""

data.plot.scatter(x='Quantity', y='Price')

"""####Observations
#####The boxplot shows how Price varies across different Quantity values. Most prices are concentrated within the interquartile range, with a few outliers. It helps identify variations and extreme values in Price for each Quantity level.

"""

sns.boxplot(data=data, x='Quantity', y="Price",color='Violet')

"""##BIVARIATE ANALYSIS-Categorical Columns

#####BIVARIENT ANALYSIS - CATEGORICAL COLUMNS

#####This the Categorical data columns this is a heatmap of categorical data
"""

categorical_data = data.select_dtypes(include=['object'])

cross_tab = pd.crosstab(data['Product_Category'], data['Payment_Method'])
plt.figure(figsize=(10, 8))
sns.heatmap(cross_tab, annot=True, fmt='d', cmap='Blues')
plt.title("Relationship between Product Category and Payment Method")
plt.show()

"""####Observations
#####This are the categorical columns
"""

categorical_data.columns

"""data.plot.scatter(x='Quantity', y='Price')

####Observations
####The count plot shows how different payment methods are used across various **product categories**. Some categories have higher counts, indicating they are more popular. The color hue division helps compare which **payment method** is most common within each category.
"""

plt.figure(figsize=(10, 6))
sns.countplot(data=data, x='Product_Category', hue='Payment_Method')
plt.title("Product Category by Country")
plt.xticks(rotation=45)
plt.show()

"""####Observations
#####The boxplot shows the price distribution across different product categories and payment methods. It highlights how prices vary within each category and which payment methods are linked to higher or lower prices. Outliers indicate unusually high or low prices in specific categories.

"""

plt.figure(figsize=(10, 6))
sns.boxplot(data=data, x='Product_Category', hue='Payment_Method')
plt.title("Product Category by Country")
plt.xticks(rotation=45)
plt.show()

"""####Observations
#####The violin plot shows the distribution of payment methods within each product category. It combines the features of a boxplot and a density plot, displaying both the range and concentration of data. Wider sections indicate where most values are concentrated, while thinner parts show fewer observations.

"""

sns.violinplot(data=data,x='Product_Category',hue='Payment_Method')
plt.show()

"""####Observations
The count plot shows how different quantities are distributed across various product categories. It helps identify which categories have higher sales volumes and which have lower ones. Taller bars indicate categories with more transactions or higher quantities sold.

"""

plt.figure(figsize=(10, 6))
sns.countplot(data=data, x='Product_Category', hue='Quantity')
plt.title("Product Category by Country")
plt.xticks(rotation=45)
plt.show()

"""####Observations
#####The pie chart shows the percentage share of each payment method in total sales. It clearly highlights which payment method is used most frequently and which are less common. Larger slices represent the more popular payment methods among customers.

"""

plt.figure(figsize=(14,7))
data['Payment_Method'].value_counts().plot.pie(autopct='%1.1f%%',figsize=(8,8))
plt.title("Pie chart of Payment_Method Sales")
plt.show()

"""##MULTIVARIATE ANALYSIS

####Observations
#####The pair plot shows the relationships between all numerical variables in the dataset, with data points colored by product category. It helps visualize correlations, trends, and group differences across categories. Clusters or clear patterns indicate relationships between certain variables.
"""

plt.figure(figsize=(20,7))
sns.pairplot(data=data, hue='Product_Category')

"""##CONCLUSION

###This project analyzed e-commerce sales data to identify trends and insights. After cleaning the data, different visualizations were used to understand product performance, customer preferences, and payment patterns. The analysis showed that specific product categories and payment methods played a major role in overall sales. The project highlights how data visualization can support better business decisions.
"""